-- Baseline schema snapshot for the KHZNTI (خزنتي) production database.
--
-- IMPORTANT: this file was NOT generated by `supabase db pull` — that
-- command (and `supabase db dump`) require a local Docker daemon to spin
-- up a shadow database for diffing, which wasn't available on this
-- machine. Every statement below was instead reconstructed from direct
-- SQL Editor queries run against the live production database on
-- 2026-09-14:
--   - information_schema.columns            (column names/types/nullability/defaults)
--   - information_schema.table_constraints  (primary keys, foreign keys)
--   - pg_policies                           (RLS policy definitions)
--   - pg_class / pg_namespace               (RLS enabled/disabled per table)
-- Nothing here is guessed or assumed. This file documents the CURRENT
-- production state (including its known imperfections, noted below) for
-- version-control purposes — it is not meant to be (re-)applied to the
-- already-existing production database.

-- ---------------------------------------------------------------------
-- public.transactions
-- ---------------------------------------------------------------------

create table public.transactions (
  id serial primary key,
  user_id uuid,
  type text,
  amount numeric,
  category text,
  account text,
  date text
);

alter table public.transactions enable row level security;

create policy "Users can view their own transactions"
  on public.transactions for select
  to public
  using (auth.uid() = user_id);

create policy "Users can insert their own transactions"
  on public.transactions for insert
  to public
  with check (auth.uid() = user_id);

create policy "Users can update their own transactions"
  on public.transactions for update
  to public
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own transactions"
  on public.transactions for delete
  to public
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- public.debts
-- ---------------------------------------------------------------------

create table public.debts (
  id serial primary key,
  user_id uuid,
  type text,
  name text,
  amount numeric,
  paid numeric,
  date text,
  due_date date
);

alter table public.debts enable row level security;

create policy "Enable select for debts"
  on public.debts for select
  to public
  using (auth.uid() = user_id);

create policy "Enable insert for debts"
  on public.debts for insert
  to public
  with check (auth.uid() = user_id);

create policy "Users can update their own debts"
  on public.debts for update
  to public
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Written by an earlier dashboard policy edit as a scalar subquery
-- rather than a bare function call — functionally identical to
-- `auth.uid() = user_id`, kept as-is to match the confirmed source
-- exactly rather than "normalizing" it.
create policy "Enable delete for users based on user_id"
  on public.debts for delete
  to public
  using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------
-- Confirmed gaps in the current schema (documented, not fixed here):
--
-- 1. No NOT NULL constraints anywhere except the `id` primary keys.
--    user_id, type, amount, category, etc. can all be NULL at the
--    database level — every one of these is only enforced by
--    application-side validation in App.jsx, not by the schema itself.
--
-- 2. No foreign key from either table's user_id to auth.users(id).
--    RLS (auth.uid() = user_id) still isolates data correctly per user,
--    but the database has no referential-integrity guarantee that a
--    stored user_id corresponds to a real auth user.
--
-- 3. No CHECK constraint on `type` in either table. The app only
--    recognizes specific string values ("دخل", "مصروف", "مبيعات",
--    "شراء" for transactions; "دين له", "دين عليه" for debts) — any
--    other string could be inserted without the database objecting,
--    and would silently fail to be categorized as income/expense by
--    the app's own logic.
--
-- 4. Inconsistent date typing: `date` is a plain `text` column on both
--    tables (app stores "YYYY-MM-DD" strings), while `debts.due_date`
--    is a real Postgres `date` column. Historical inconsistency, not
--    an active bug.
-- ---------------------------------------------------------------------
